accordion/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'accordion'

urlpatterns = [
    path('accordion/', views.accordion, name='accordion')
]

activity/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'activity'

urlpatterns = [
    path('activity/', views.activityview, name='activityview'),
    path('formactivity/',views.activityform, name='activityform'),
    path('formaddactivity/',views.addactivityform, name='addactivityform')
]

authen/urls.py
from django.urls import path
from django.conf.urls import url
from . import views


app_name = 'authen'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.userlogin, name='login'),
    path('logout/', views.userlogout, name='logout')
]

books/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'books'

urlpatterns = [
    path('books/', views.books, name='books'),
    path('booksdata/',views.booksdata, name='booksdata')
]

main/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('jadwal/', views.createJadwal, name='jadwal'),
    path('jadwalview/', views.viewJadwal, name='jadwalview'),
    path('delete/<int:pk>/', views.deleteJadwal, name='delete'),
]

rafimorenoppw/urls.py
from django.contrib import admin
from django.urls import include, path
from main.views import about, story1, story3, story3gallery, createJadwal, viewJadwal

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('jadwal/',createJadwal),
    path('jadwalview/',viewJadwal),
    path('', include('activity.urls')),
    path('', include('accordion.urls')),
    path('', include('books.urls')),
    path('', include('authen.urls'))
]

accordion/models.py
from django.db import models

# Create your models here.

activity/models.py
from django.db import models

class Activity(models.Model):
    nama = models.CharField(max_length = 30)
    
    def __str__(self):
        return self.nama

class Participant(models.Model):
    nama = models.CharField(max_length = 50)
    nama_Kegiatan = models.ForeignKey(Activity, null = True, on_delete=models.CASCADE)

    def __str__(self):
        return self.nama

authen/models.py
from django.db import models

# Create your models here.

books/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models

class Jadwal(models.Model):
    nama_Matkul = models.CharField(max_length = 75)
    dosen = models.CharField(max_length = 75)
    sks = models.CharField(max_length = 2)
    semester_Tahun = models.CharField(max_length = 50)
    deskripsi_Matkul = models.TextField()

activity/forms.py
from django import forms
from .models import Activity, Participant

class ParticipantForm(forms.ModelForm):
    class Meta:
        model = Participant
        fields = [
            'nama',
            'nama_Kegiatan'
        ]
        

class ActivityForm(forms.ModelForm):
    class Meta:
        model = Activity
        fields = [
            'nama'
        ]
        

        
        

authen/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

main/forms.py
from django import forms
from .models import Jadwal

class JadwalForm(forms.ModelForm):
    class Meta:
        model = Jadwal
        fields = [
            'nama_Matkul',
            'dosen',
            'sks',
            'semester_Tahun',
            'deskripsi_Matkul'
        ]
        widgets = {
            'nama_Matkul' : forms.TextInput(attrs={'class' : 'form-control'}),
            'dosen' : forms.TextInput(attrs={'class' : 'form-control'}),
            'sks' : forms.TextInput(attrs={'class' : 'form-control'}),
            'semester_Tahun' : forms.TextInput(attrs={'class' : 'form-control'}),
            'deskripsi_Matkul' : forms.Textarea(attrs={'class' : 'form-control'})
        }

accordion/views.py
from django.shortcuts import render

def accordion(request):
    return render(request, 'accordion/accordion.html')

activity/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *
# Create your views here.
def activityview(request):
    activity = Activity.objects.all()
    participant = Participant.objects.all()
    context = { 'activity' : activity,
                'participant' : participant
     }
    return render(request, 'activity/view.html', context)

def activityform(request):
    form = ParticipantForm()

    if request.method == 'POST':
        form = ParticipantForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/activity')

    context = {'form' : form }
    return render(request, 'activity/formkegiatan.html', context)

def addactivityform(request):
    form = ActivityForm()

    if request.method == 'POST':
        form = ActivityForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/formactivity')

    context = {'form' : form }
    return render(request, 'activity/formtambahkegiatan.html', context)

authen/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from .forms import *
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout

def register(request):
    if request.user.is_authenticated:
        return redirect('/')
    else:
        form = CreateUserForm()
        
        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                username = form.cleaned_data.get('username')
                messages.success(request, 'Account Succesfully Registered')
                return redirect('/login/')
            else:
                messages.warning(request, 'Password does not fulfill requirements')
    
        context = {'form' : form}
        return render(request, 'authen/register.html', context)

def userlogin(request):
    if request.user.is_authenticated:
        return redirect('/')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username , password=password)

            if user is not None:
                login(request, user)
                messages.success(request, 'User ' + username + ' has successfully logged in')
                return redirect('/')
            else:
                messages.warning(request, 'Username / Password does not match ')
        
        context = {}
        return render(request, 'authen/login.html', context)

def userlogout(request):
    logout(request)
    return redirect('/login/')

books/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests
import json

def books(request):
    return render(request, 'books/books.html')

def booksdata(request):
    arg = request.GET['q']
    url = 'https://www.googleapis.com/books/v1/volumes?q=' + arg
    re = requests.get(url)
    data = json.loads(re.content)
    return JsonResponse(data, safe=False)

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import JadwalForm
from .models import Jadwal


def home(request):
    return render(request, 'main/home.html')

def about(request):
    return render(request, 'main/about.html')

def story1(request):
    return render(request, 'main/Story1.html')

def story3(request):
    return render(request, 'main/Story3.html')

def story3gallery(request):
    return render(request, 'main/Story3Gallery.html')

def createJadwal(request):
    form = JadwalForm()

    if request.method == 'POST':
        form = JadwalForm(request.POST)
        if form.is_valid():
            form.save()
            form = JadwalForm()

    context = {'form' : form }
    
    return render(request, 'main/Jadwal.html', context)

def viewJadwal(request):
    form = Jadwal.objects.all()
    context = {'form' : form }
    return render(request, 'main/jadwalview.html', context)

def deleteJadwal(request, pk):
    form = Jadwal.objects.get(id=pk)
    if request.method == "POST":
        form.delete()
        return redirect('/jadwalview')
    context = {'form' : form }
    return render(request, 'main/delete.html', context)

accordion/templates/accordion/accordion.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Accordion</title>
{% endblock meta %}

{% block content %}
<div class="container">
    <div class="s7_accordion">
        <div class="s7_accordionitem">
            <div class="s7_accordionhead">
                <p>AKU</p>
                <div class="s7_arrows">
                    <p class="s7_up">V</p>
                    <p class="s7_down">V</p>
                </div>
            </div>
                <div class="s7panel">
                    <p>Satu</p>
                </div>
                
        </div>

    <div class="s7_accordionitem">
        <div class="s7_accordionhead">
            <p>LELAH</p>
            <div class="s7_arrows">
                <p class="s7_up">V</p>
                <p class="s7_down">V</p>
            </div>
            </div>
            <div class="s7panel">
                <p>Dua</p>
            </div>
    </div>

    <div class="s7_accordionitem">
        <div class="s7_accordionhead">
            <p>SEKALI</p>
            <div class="s7_arrows">
                <p class="s7_up">V</p>
                <p class="s7_down">V</p>
            </div>
        </div>
            <div class="s7panel">
                <p>Tiga</p>
            </div>
        </div>

    <div class="s7_accordionitem">
        <div class="s7_accordionhead">
            <p>HEHE</p>
            <div class="s7_arrows">
                <p class="s7_up">V</p>
                <p class="s7_down">V</p>
            </div>
        </div>
            <div class="s7panel">
                <p>Empat</p>
            </div>
        </div>

    </div>
</div>
{% endblock content %}

activity/templates/activity/formkegiatan.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Form Activity</title>
{% endblock meta %}

{% block content %}
<div class='s6'>
    <div class='container'>
        <h1>Lagi Ngapain ?</h1>
        <div class='form-group'>
                <form method='POST'>
                    {% csrf_token %}
                    {{form.as_p}}
                    <input  type="submit" value="Submit">
                </form>
        </div>
        <a class="btn btn-secondary" href="{% url 'activity:addactivityform' %}" role="button">Tambah Kegiatan</a>
    </div>
</div>

{% endblock content %}

activity/templates/activity/formtambahkegiatan.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Form Add Activity</title>
{% endblock meta %}

{% block content %}
<div class='s6addactivity'>
    <div class='container'>
        <h1>Tambah Kegiatan</h1>
        <div class='form-group'>
                <form method='POST'>
                    {% csrf_token %}
                    {{form.as_p}}
                    <input  type="submit" value="Submit">
                </form>
        </div>
    </div>
</div>

{% endblock content %}

activity/templates/activity/view.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Activity</title>
{% endblock meta %}

{% block content %}
<div class="s6view">
<div class="container">
<h1>Daftar Kegiatan dan Peserta</h1>
{% for q in activity %}
    <table class="table table-bordered">
            <tr>
                <th>{{q.nama}}</th>
            </tr>
                {% for participant in q.participant_set.all %}
                    <tr>
                        <td>{{participant}}</td>
                    </tr>
                {% endfor %}
      </table>
{% endfor %}
    </div>
</div>
{% endblock content %}

authen/templates/authen/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Register Account</title>
{% endblock meta %}

{% block content %}
<div class="s9_login">
<div class="page-container">
    <h1>LOGIN</h1>
<div class="s9_loginbox">
<form method="POST" action="">
{% csrf_token %}
    <label for="username">Username : </label>
    <input type="text" id="username" name="username" class="form-control"><br><br>
    <label for="password">Password : </label>
    <input type="password" id="password" name="password" class="form-control"><br><br>
    <input id="s9_submitlogin" type="submit" value="Login">
</form>
</div>
</div>
</div>
{% endblock content %}

authen/templates/authen/register.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Register Account</title>
{% endblock meta %}

{% block content %}
<div class="s9_register">
    <h1> MAKE YOUR ACCOUNT HERE </h1>
<div class="page-container">
    <div class="s9_registerbox">
    <form method="POST" action="">
        {% csrf_token %}
        <ul>
            <li><label>Username : </label>
            {{form.username}}</li>
        </ul>

        <ul>
            <li><label>Email : </label>
            {{form.email}}</li>
        </ul>

        <ul>
            <li><label>Password : </label>
            {{form.password1}}</li>
        </ul>

        <ul>
            <li><label>Confirm Password : </label>
            {{form.password2}}</li>
            <input id="s9_submitregis" type="submit" value="Create Account">
        </ul>
    </form>
    </div>

    <div class="s9_passreqbox">
        <ul>
            <li> Your password can’t be too similar to your other personal information.</li>
            <li> Your password must contain at least 8 characters.</li>
            <li>Your password can’t be a commonly used password.</li>
            <li> Your password can’t be entirely numeric.</li>
        </ul>
    </div>

</div>
</div>

{% endblock content %}

books/templates/books/books.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Books</title>
{% endblock meta %}

{% block content %}
<div class="container">
    <div class="s8_search">
        <h1>Book Search</h1>
        <input type="text" id="s8_searchbox">
        <ol id="hasil"></ol>
    </div>
</div>
{% endblock content %}

main/templates/main/Jadwal.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Jadwal</title>
{% endblock meta %}

{% block content %}
<div class='s5'>
<div class='container'>
    <h1>Yuk Buat Jadwal !</h1>
    <div class='form-group'>
            <form method='POST'>
                {% csrf_token %}
                {{form.as_p}}
                <input  type="submit" value="Submit">
            </form>  
    </div>
</div>
</div>
{% endblock content %}

main/templates/main/Story1.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 1</title>
{% endblock meta %}

{% block content %}
<div class='container'>
<div class="s1body">
<h1>Selamat Datang di Profile Saya!</h1>
    <div class="s1profile">
        <img src="{% static 'imgstory1/IMG_20190809_1756332.jpg' %}">
        <p>Nama : Ahmadar Rafi Moreno</p>
        <p>NPM : 1906398540</p>
        <p>Angkatan : 2019</p>
        <p>Kuliah : Universitas Indonesia</p>
        <p>Hobi : Nonton Film, Bermain Game</p>
        <p>Deskripsi Saya : Seorang kelahiran 2001 yang sering tidur dan bercita-cita ingin mempunyai perusahaan sendiri</p>
    </div>
      <div class="s1table">
        <h2>Tabel Riwayat Pendidikan</h2>
        <table>
            <tr>
                <th>Jenjang</th>
                <th>Nama Sekolah</th>
              </tr>
              <tr>
                <td>SD</td>
                <td>SD Al-Azhar 17 Bintaro</td>
              </tr>
              <tr>
                <td>SMP</td>
                <td>SMP Al-Azhar 3 Bintaro</td>
              </tr>
              <tr>
                <td>SMA</td>
                <td>SMA Negeri 34 Jakarta</td>
            </tr>
            <tr>
                <td>Perguruan Tinggi</td>
                <td>Universitas Indonesia</td>
            </tr>
        </table>
      </div>
      <div class="s1socmed">
      <h3>My Social Media</h3>
        <a href="https://www.instagram.com/rafi.morrr/"><img src="{% static 'imgstory1/600px-Instagram_logo_2016.svg.png' %}"></a>
        <a href="https://twitter.com/rafimorrr_"><img src="{% static 'imgstory1/Twitter logo 2012.png' %}" ></a>
      </div>
  </div>
</div>
{% endblock content %}

main/templates/main/Story3.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 3</title>
{% endblock meta %}

{% block content %}
<div class="container">
<div class="s3prof">
    <div class="bioprof d-flex flex-column flex-md-row">
        <div class="s3profpic col-4">
            <img src="{% static 'imgstory1/IMG_20190809_1756332.jpg' %}">
        </div>
    <div class="s2bio col-6">
        <div class="rect">
            <div class="s3bio1">
                <div class="header">
                    <p>Ahmadar Rafi Moreno</p>
                </div>
            </div>
        </div>
        <div class="rect">
            <div class="s3bio2">
            <p>NPM : 1906398540</p>
            <p>Angkatan : 2019</p>
            <p>Kuliah : Universitas Indonesia</p>
            <p>Hobi : Nonton Film, Bermain Game</p>
            <p>Deskripsi Saya : Mau Tidur</p>
            </div>
        </div>
    </div>
    </div>
</div>
<div class="s3table">
    <div class="row">
        <div class="table-responsive col-md-6">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th colspan="2">Riwayat Kepanitiaan/Organisasi</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>HSC SMAN 34</td>
                        <td>Divisi Perlengkapan</td>
                    </tr>
                    <tr>
              <td>BETIS FASILKOM UI</td>
              <td>Divisi Perlengkapan</td>
            </tr>
             <tr>
              <td>RISTEK FASILKOM UI</td>
              <td>Human Resources Division</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="table-responsive col-md-6">
        <table class="table table-bordered">
          <thead>
            <tr>
                <th colspan="2">Riwayat Pendidikan</th>
            </tr>
          </thead>
          <tbody>
            <tr>
                <td>SD</td>
                <td>SD Islam Al-Azhar 17 Bintaro</td>
              </tr>
            <tr>
              <td>SMP</td>
              <td>SMP Islam Al-Azhar 3 Bintaro</td>
            </tr>
            <tr>
              <td>SMA</td>
              <td>SMA Negeri 34 Jakarta</td>
            </tr>
             <tr>
              <td>Perguruan Tinggi</td>
              <td>Universitas Indonesia</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
</div>
    <div class="s3socmed">
        <p>My Social Media</p>
        <div class="col">
            <a  href="https://open.spotify.com/user/fe2sfm6jnjdc9w9lpg4tes0cq?si=kNlYW0pgTI6la6lSk2KO2A"><img src="{% static 'iconstory3/1200px-Spotify_logo_without_text.svg.png' %}" class="rounded-circle"></a>
            <a  href="https://twitter.com/rafimorrr_"><img src="{% static 'iconstory3/1200px-Twitter.png' %}" class="rounded-circle"></a>
            <a  href="https://www.instagram.com/rafi.morrr/"><img src="{% static 'iconstory3/1200px-Instagram-Icon.png' %}" class="rounded-circle"></a>
            <a  href="https://www.linkedin.com/in/ahmadar-rafi-moreno-89a0b01a3/"><img src="{% static 'iconstory3/1200px-Linkedin.svg.png' %}" class="rounded-circle"></a>
            <a  href="https://steamcommunity.com/id/Kutubberuang/"><img src="{% static 'iconstory3/1200px-Steam_icon_logo.svg (1).png' %}" class="rounded-circle"></a>
        </div>
    </div>
</div>
{% endblock content %}

main/templates/main/Story3Gallery.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 3 Gallery</title>
{% endblock meta %}

{% block content %}
<div class="container">
<div class="gal">
    <div class="gal_title">
        <span class="label"></span>
    </div>
    <div class="fotofoto">
        <div class="row">
            <div class="column">
                <img src="{% static 'imgstory3/gallery1.jpg' %}">
            </div>
            <div class="column">
                <img src="{% static 'imgstory3/gallery2.jpg' %}">
            </div>
            <div class="column">
                <img src="{% static 'imgstory3/gallery3.gif' %}">
            </div>
        </div>
        <div class="row">
            <div class="column">
                <img src="{% static 'imgstory3/gallery4.jpg' %}">
            </div>
            <div class="column">
                <img src="{% static 'imgstory3/gallery5.jpg' %}">
            </div>
            <div class="column">
                <img src="{% static 'imgstory3/gallery6.gif' %}">
            </div>
        </div>
    </div>
</div>
</div>
{% endblock content %}

main/templates/main/about.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>About</title>
{% endblock meta %}

{% block content %}
<div class="container">
    <div class="aboutbox">
        <img src="{% static 'img/CN06.jpg' %}">
        <p>Nama : Ahmadar Rafi Moreno</p>
        <p>TTL : Jakarta, 4 Juni 2001</p>
        <p>Pekerjaan : Mahasiswa</p>
        <p>Kuliah : Universitas Indonesia</p>
        <p>Bidang Studi : Ilmu Komputer</p>
    </div>
</div>
  
{% endblock content %}

main/templates/main/delete.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Confirm Delete</title>
{% endblock meta %}

{% block content %}
<div class="s5confirm">
    <div class="container">
        <h1> Are you sure you want to delete {{form.nama_Matkul}} ? </h1>
        <form method="POST" action="{% url 'main:delete' form.pk %}"> 
        {% csrf_token %}
            <input type="submit" value="Yes">
        </form>
    </div>
</div>
{% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Homepage</title>
{% endblock meta %}

{% block content %}
<div class="box">
    <h2>WELCOME</h2>
    <h3>This Is Rafi Moreno's PPW Website</h3>
</div>
{% endblock content %}

main/templates/main/jadwalview.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Jadwal</title>
{% endblock meta %}

{% block content %}
<div class="s5view">
<div class="container">
    <h1>Jadwal Saya</h1>
    <table class="table table-bordered">
            <tr>
                <th>Matkul</th>
                <th>Nama Dosen</th>
                <th>SKS</th>
                <th>Semester</th>
                <th>Deskripsi</th>
            </tr>
            {% for q in form %}
                <tr>
                    <td>{{q.nama_Matkul}}</td>
                    <td>{{q.dosen}}</td>
                    <td>{{q.sks}}</td>
                    <td>{{q.semester_Tahun}}</td>
                    <td>{{q.deskripsi_Matkul}}</td>
                    <td><a href="{% url 'main:delete' q.pk %}" class="btn btn-secondary btn-sm active" role="button" aria-pressed="true">Delete</a></td>
                </tr>
            {% endfor %}
      </table>
    </div>
</div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <link href='https://fonts.googleapis.com/css?family=Oswald' rel='stylesheet'>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="{% static 'js/jees.js' %}"></script>
  {% block meta %}
  {% endblock meta %}
</head>

<body>
<div class="page-container">
  <div class="content-wrap">
    <nav class="navbar navbar-expand-lg">
      <a class="navbar-brand" href="{% url 'main:home' %}">RafiMoreno</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"><i class="fa fa-navicon"></i></i></span>
      </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accordion:accordion' %}">Accordion</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'books:books' %}">Book Search</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Jadwal
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'main:jadwal' %}">Create</a>
          <a class="dropdown-item" href="{% url 'main:jadwalview' %}">View</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Activity
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'activity:activityform' %}">Create</a>
          <a class="dropdown-item" href="{% url 'activity:activityview' %}">View</a>
        </div>
      </li>
      </ul>
      <ul class="nav navbar-nav ml-auto">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="#">{{user.username}} Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'authen:logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'authen:register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'authen:login' %}">Login</a>
        </li>
        {% endif %}
      
      </ul>
    </div>
  </nav>
  {% if messages %}
  {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
      {{ message }}
    </div>
  {% endfor %}
  {% endif %}
  {% block content %}
  {% endblock content %}
</div>
  <footer id="footer"></footer>
</div>
</body>
</html>